In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_PATH = Path("../data/raw/NIFTY50_all.csv")

stocks_df = pd.read_csv(DATA_PATH)

print(stocks_df.shape)
stocks_df.head()

(235192, 15)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,NaN,9859619.0,0.3612
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,NaN,1453278.0,0.3172
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,NaN,1069678.0,0.2088
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,NaN,1260913.0,0.2735
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,NaN,816123.0,0.2741

In [2]:
stocks_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  str
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 26.9 MB

In [3]:
stocks_df.describe()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05,1.203440e+05,2.191150e+05,219115.000000
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.388302,1266.554351,1267.13230,3.045903e+06,1.610138e+14,6.196427e+04,1.315098e+06,0.502997
std,2581.370320,2585.259609,2619.649216,2546.621396,2581.392543,2582.140942,2582.69998,7.333981e+06,3.298085e+14,6.866457e+04,2.831670e+06,0.190019
min,0.000000,8.500000,9.750000,8.500000,9.100000,9.150000,9.21000,3.000000e+00,1.047000e+07,1.100000e+01,5.000000e+00,0.023600
25%,274.300000,275.000000,279.500000,269.600000,274.400000,274.350000,274.69750,2.190095e+05,1.612816e+13,2.183400e+04,1.253830e+05,0.364700
50%,566.500000,567.025000,576.900000,556.500000,567.000000,566.700000,566.94000,1.010938e+06,6.832603e+13,4.406800e+04,5.017560e+05,0.511000
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.900000,1242.400000,1242.66250,3.019851e+06,1.863835e+14,7.893550e+04,1.452233e+06,0.638400
max,32861.950000,33399.950000,33480.000000,32468.100000,32849.000000,32861.950000,32975.24000,4.810589e+08,3.564334e+16,1.643015e+06,2.325307e+08,1.000000

In [4]:
stocks_df.columns.tolist()

['Date',
 'Symbol',
 'Series',
 'Prev Close',
 'Open',
 'High',
 'Low',
 'Last',
 'Close',
 'VWAP',
 'Volume',
 'Turnover',
 'Trades',
 'Deliverable Volume',
 '%Deliverble']

In [5]:
stocks_df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

In [6]:
print("Duplicate rows:", stocks_df.duplicated().sum())

Duplicate rows: 0

In [7]:
stocks_df["Date"].dtype

In [8]:
stocks_df["Date"] = pd.to_datetime(stocks_df["Date"])

In [9]:
stocks_df["Date"].dtype

dtype('<M8[us]')

In [12]:
metadata = pd.read_csv("../data/metadata/stock_metadata.csv")

metadata.head()

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Ports and Special Economic Zone Ltd.,SERVICES,ADANIPORTS,EQ,INE742F01042
1,Asian Paints Ltd.,CONSUMER GOODS,ASIANPAINT,EQ,INE021A01026
2,Axis Bank Ltd.,FINANCIAL SERVICES,AXISBANK,EQ,INE238A01034
3,Bajaj Auto Ltd.,AUTOMOBILE,BAJAJ-AUTO,EQ,INE917I01010
4,Bajaj Finserv Ltd.,FINANCIAL SERVICES,BAJAJFINSV,EQ,INE918I01018

In [13]:
symbol_mapping = {
    "MUNDRAPORT": "ADANIPORTS",
    "UTIBANK": "AXISBANK",
    "BAJAUTOFIN": "BAJFINANCE",
    "BHARTI": "BHARTIARTL",
    "HEROHONDA": "HEROMOTOCO",
    "HINDALC0": "HINDALCO",
    "HINDLEVER": "HINDUNILVR",
    "INFOSYSTCH": "INFY",
    "JSWSTL": "JSWSTEEL",
    "KOTAKMAH": "KOTAKBANK",
    "TELCO": "TATAMOTORS",
    "TISCO": "TATASTEEL",
    "UNIPHOS": "UPL",
    "SESAGOA": "VEDL",
    "SSLT": "VEDL",
    "ZEETELE": "ZEEL"
}

In [14]:
stocks_df["Symbol"] = stocks_df["Symbol"].replace(symbol_mapping)

In [15]:
stock_symbols = set(stocks_df["Symbol"].unique())
metadata_symbols = set(metadata["Symbol"].unique())

print("Symbols missing in metadata:")
print(stock_symbols - metadata_symbols)

Symbols missing in metadata:
set()

In [16]:
stocks_df = stocks_df.merge(
    metadata,
    on="Symbol",
    how="left"
)

In [17]:
stocks_df[["Symbol", "Company Name", "Industry", "ISIN Code"]].head()

,Symbol,Company Name,Industry,ISIN Code
0,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
1,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
2,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
3,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
4,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042

In [18]:
stocks_df[["Company Name", "Industry", "ISIN Code"]].isnull().sum()

Company Name    0
Industry        0
ISIN Code       0
dtype: int64

In [19]:
print("Dataset Shape:", stocks_df.shape)

print("\nUnique Stocks:", stocks_df["Symbol"].nunique())

print("\nDate Range:")
print(stocks_df["Date"].min())
print(stocks_df["Date"].max())

stocks_df.info()

Dataset Shape: (235192, 19)

Unique Stocks: 49

Date Range:
2000-01-03 00:00:00
2021-04-30 00:00:00
<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  datetime64[us]
 1   Symbol              235192 non-null  str
 2   Series_x            235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
 15  Company Name        235192 non-null  str
 16  Industry            235192 non-null  str
 17  Series_y            235192 non-null  str
 18  ISIN Code           235192 non-null  str
dtypes: datetime64[us](1), float64(11), int64(1), str(6)
memory usage: 34.1 MB

In [20]:
stocks_df.head()

,Date,Symbol,Series_x,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Company Name,Industry,Series_y,ISIN Code
0,2012-01-17,ADANIPORTS,EQ,135.5,137.1,141.00,135.00,140.1,140.00,138.13,1636196,2.260074e+13,18374.0,1004327.0,0.6138,Adani Ports and Special Economic Zone Ltd.,SERVICES,EQ,INE742F01042
1,2012-01-18,ADANIPORTS,EQ,140.0,142.0,143.80,138.70,143.0,141.70,141.25,890591,1.257986e+13,15615.0,404925.0,0.4547,Adani Ports and Special Economic Zone Ltd.,SERVICES,EQ,INE742F01042
2,2012-01-19,ADANIPORTS,EQ,141.7,144.0,150.55,143.15,149.5,149.40,146.72,1456077,2.136382e+13,31299.0,721545.0,0.4955,Adani Ports and Special Economic Zone Ltd.,SERVICES,EQ,INE742F01042
3,2012-01-20,ADANIPORTS,EQ,149.4,151.9,157.60,150.25,155.4,155.40,153.76,1634070,2.512583e+13,23335.0,861145.0,0.5270,Adani Ports and Special Economic Zone Ltd.,SERVICES,EQ,INE742F01042
4,2012-01-23,ADANIPORTS,EQ,155.4,155.4,155.40,145.10,146.4,146.75,149.54,1657609,2.478768e+13,12400.0,820653.0,0.4951,Adani Ports and Special Economic Zone Ltd.,SERVICES,EQ,INE742F01042

In [21]:
(stocks_df["Series_x"] == stocks_df["Series_y"]).value_counts(dropna=False)

True    235192
Name: count, dtype: int64

In [22]:
# Rename Series_x to Series
stocks_df.rename(columns={"Series_x": "Series"}, inplace=True)

# Drop the duplicate column
stocks_df.drop(columns=["Series_y"], inplace=True)

In [23]:
stocks_df.columns

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble', 'Company Name', 'Industry', 'ISIN Code'],
      dtype='str')

In [24]:
stocks_df = stocks_df.sort_values(
    by=["Symbol", "Date"]
).reset_index(drop=True)

In [25]:
stocks_df.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Company Name,Industry,ISIN Code
0,2007-11-27,ADANIPORTS,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,NaN,9859619.0,0.3612,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
1,2007-11-28,ADANIPORTS,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,NaN,1453278.0,0.3172,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
2,2007-11-29,ADANIPORTS,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,NaN,1069678.0,0.2088,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
3,2007-11-30,ADANIPORTS,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,NaN,1260913.0,0.2735,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042
4,2007-12-03,ADANIPORTS,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,NaN,816123.0,0.2741,Adani Ports and Special Economic Zone Ltd.,SERVICES,INE742F01042

In [27]:
print(stocks_df.shape)

(235192, 18)

In [28]:
stocks_df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
Company Name               0
Industry                   0
ISIN Code                  0
dtype: int64

In [29]:
stocks_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  datetime64[us]
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
 15  Company Name        235192 non-null  str
 16  Industry            235192 non-null  str
 17  ISIN Code           235192 non-null  str
dtypes: datetime64[us](1), float64(11), int64(1), str(5)
memory usage: 32.3 MB

In [30]:
print("Unique Symbols:", stocks_df["Symbol"].nunique())

Unique Symbols: 49

In [31]:
print("Start Date:", stocks_df["Date"].min())
print("End Date:", stocks_df["Date"].max())

Start Date: 2000-01-03 00:00:00
End Date: 2021-04-30 00:00:00

In [32]:
stocks_df.to_csv(
    "../data/processed/cleaned_stock_data.csv",
    index=False
)